# Generated by Django 5.0.3 on 2024-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Ncart', models.CharField(max_length=15)),
                ('Prod_SCart', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_name', models.CharField(max_length=15)),
                ('Prod_cost', models.IntegerField()),
                ('Prod_Sale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Passw', models.CharField(max_length=8)),
            ],
        ),
    ]
