# Generated by Django 5.0.3 on 2024-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_rename_prod_scart_carrito_prod_scart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Prod_name',
            field=models.CharField(max_length=50),
        ),
    ]
