# Generated by Django 5.0.3 on 2024-03-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_alter_productos_prod_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('slname', models.CharField(max_length=50)),
                ('sstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
