# Generated by Django 5.0.3 on 2024-03-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='scateg',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
