# Generated by Django 5.0.3 on 2024-03-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_staff_scateg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='Usuario',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='registro',
            name='lname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
