# Generated by Django 5.0.3 on 2024-04-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_proveedores_delete_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='GIRO',
            new_name='Giro',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='RUT',
            new_name='Rut',
        ),
    ]
